### ISSUE TITLE
FileNotFoundError during build

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/rlocker#2]
I am encountering the following FileNotFoundError when attempting to build the project using python 3.9.

```python
$ python -m build ./
Found existing installation: setuptools 56.0.0
Uninstalling setuptools-56.0.0:
  Successfully uninstalled setuptools-56.0.0
Collecting setuptools>=40.8.0
  Downloading setuptools-57.2.0-py3-none-any.whl (818 kB)
     |████████████████████████████████| 818 kB 1.9 MB/s
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-57.2.0 wheel-0.36.2
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/private/var/folders/cm/qrs4d_9j4dq5j6hj3snm72qm0000gn/T/build-env-jmk0eefv/bin/python -m pip install --upgrade pip' command.
running egg_info
creating rlockertools.egg-info
writing rlockertools.egg-info/PKG-INFO
writing dependency_links to rlockertools.egg-info/dependency_links.txt
writing entry points to rlockertools.egg-info/entry_points.txt
writing requirements to rlockertools.egg-info/requires.txt
writing top-level names to rlockertools.egg-info/top_level.txt
writing manifest file 'rlockertools.egg-info/SOURCES.txt'
reading manifest file 'rlockertools.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'rlockertools.egg-info/SOURCES.txt'
running sdist
running egg_info
writing rlockertools.egg-info/PKG-INFO
writing dependency_links to rlockertools.egg-info/dependency_links.txt
writing entry points to rlockertools.egg-info/entry_points.txt
writing requirements to rlockertools.egg-info/requires.txt
writing top-level names to rlockertools.egg-info/top_level.txt
reading manifest file 'rlockertools.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'rlockertools.egg-info/SOURCES.txt'
running check
creating rlockertools-0.3.9
creating rlockertools-0.3.9/framework
creating rlockertools-0.3.9/rlockertools
creating rlockertools-0.3.9/rlockertools.egg-info
copying files to rlockertools-0.3.9...
copying LICENSE.txt -> rlockertools-0.3.9
copying README.md -> rlockertools-0.3.9
copying setup.py -> rlockertools-0.3.9
copying framework/__init__.py -> rlockertools-0.3.9/framework
copying framework/main.py -> rlockertools-0.3.9/framework
copying rlockertools/__init__.py -> rlockertools-0.3.9/rlockertools
copying rlockertools/exceptions.py -> rlockertools-0.3.9/rlockertools
copying rlockertools/resourcelocker.py -> rlockertools-0.3.9/rlockertools
copying rlockertools/utils.py -> rlockertools-0.3.9/rlockertools
copying rlockertools.egg-info/PKG-INFO -> rlockertools-0.3.9/rlockertools.egg-info
copying rlockertools.egg-info/SOURCES.txt -> rlockertools-0.3.9/rlockertools.egg-info
copying rlockertools.egg-info/dependency_links.txt -> rlockertools-0.3.9/rlockertools.egg-info
copying rlockertools.egg-info/entry_points.txt -> rlockertools-0.3.9/rlockertools.egg-info
copying rlockertools.egg-info/requires.txt -> rlockertools-0.3.9/rlockertools.egg-info
copying rlockertools.egg-info/top_level.txt -> rlockertools-0.3.9/rlockertools.egg-info
Writing rlockertools-0.3.9/setup.cfg
Creating tar archive
removing 'rlockertools-0.3.9' (and everything under it)
Found existing installation: setuptools 56.0.0
Uninstalling setuptools-56.0.0:
  Successfully uninstalled setuptools-56.0.0
Collecting setuptools>=40.8.0
  Using cached setuptools-57.2.0-py3-none-any.whl (818 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-57.2.0 wheel-0.36.2
WARNING: You are using pip version 21.1.1; however, version 21.1.3 is available.
You should consider upgrading via the '/private/var/folders/cm/qrs4d_9j4dq5j6hj3snm72qm0000gn/T/build-env-nfm5wd4k/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/Users/clacroix/workspace/rlockertools/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/Users/clacroix/workspace/rlockertools/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/clacroix/workspace/rlockertools/venv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/private/var/folders/cm/qrs4d_9j4dq5j6hj3snm72qm0000gn/T/build-env-nfm5wd4k/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
    return self._get_build_requires(
  File "/private/var/folders/cm/qrs4d_9j4dq5j6hj3snm72qm0000gn/T/build-env-nfm5wd4k/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/cm/qrs4d_9j4dq5j6hj3snm72qm0000gn/T/build-env-nfm5wd4k/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/private/var/folders/cm/qrs4d_9j4dq5j6hj3snm72qm0000gn/T/build-env-nfm5wd4k/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 6, in <module>
    with open("HISTORY.md") as history_file:
FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.md'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by clacroix12** [comment]
Opened in the wrong repository, going to open in rlockertools.
